"""
Executive Dark Pattern Audit Report Generator
Generates standalone, executive-grade HTML Audit Reports containing:
- Risk Score & Severity Assessment
- Multi-Modal Findings (DOM, Vision, Voice)
- International Legal Violation Citations (FTC / DSA / GDPR / UCPD)
- Remediation Guidance for Developers
"""

import json
from typing import Dict, Any, List

def generate_audit_report_html(data: Dict[str, Any]) -> str:
    """Generates complete executive HTML Audit Report."""
    url = data.get("url", "Target Domain")
    findings = data.get("findings", [])
    risk = data.get("risk_assessment", {})
    annotated_img = data.get("annotated_screenshot", "")

    risk_score = risk.get("risk_score", 0)
    risk_level = risk.get("risk_level", "UNKNOWN")
    threat_color = risk.get("threat_color", "#16a34a")

    findings_rows = ""
    for idx, f in enumerate(findings, 1):
        cat = f.get("category", "")
        conf = int(f.get("confidence", 0) * 100)
        mods = ", ".join(f.get("modalities", []))
        legal = f.get("legal_info", {})
        evidence = " · ".join(f.get("evidence", [])) if isinstance(f.get("evidence"), list) else f.get("evidence", "")

        findings_rows += f"""
        <tr>
          <td><strong>#{idx}</strong></td>
          <td><span class="badge" style="background:{threat_color};color:#fff;">{cat}</span></td>
          <td><strong>{conf}%</strong></td>
          <td><code>{mods}</code></td>
          <td>{evidence}</td>
          <td>
            <strong>{legal.get('law_title', 'Consumer Protection Law')}</strong><br>
            <small style="color:#64748b;">Citation: {legal.get('legal_citation', 'N/A')}</small>
          </td>
          <td><small style="color:#1d4ed8;">{legal.get('consumer_tip', '')}</small></td>
        </tr>
        """

    if not findings_rows:
        findings_rows = "<tr><td colspan='7' style='text-align:center;padding:20px;'>✅ No Dark Patterns Detected — Interface appears clean and compliant.</td></tr>"

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Dark Pattern Compliance Audit Report</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #f8fafc; color: #0f172a; margin: 0; padding: 40px; }}
    .report-card {{ max-width: 1000px; margin: 0 auto; background: #ffffff; border-radius: 12px; box-shadow: 0 10px 25px rgba(0,0,0,0.08); padding: 40px; border: 1px solid #e2e8f0; }}
    .header {{ display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #f1f5f9; padding-bottom: 20px; margin-bottom: 30px; }}
    h1 {{ font-size: 24px; color: #0f172a; margin: 0; }}
    .meta {{ font-size: 13px; color: #64748b; margin-top: 6px; }}
    .risk-banner {{ display: flex; align-items: center; gap: 20px; background: #f8fafc; padding: 20px; border-radius: 8px; border-left: 6px solid {threat_color}; margin-bottom: 30px; }}
    .risk-score {{ font-size: 36px; font-weight: 800; color: {threat_color}; }}
    .risk-info h3 {{ margin: 0 0 4px 0; color: #0f172a; }}
    .risk-info p {{ margin: 0; font-size: 14px; color: #475569; }}
    table {{ width: 100%; border-collapse: collapse; margin-bottom: 30px; font-size: 13px; }}
    th {{ background: #f1f5f9; text-align: left; padding: 12px 10px; color: #334155; font-weight: 700; border-bottom: 2px solid #cbd5e1; }}
    td {{ padding: 12px 10px; border-bottom: 1px solid #e2e8f0; vertical-align: top; }}
    .badge {{ padding: 3px 8px; border-radius: 4px; font-size: 11px; font-weight: 700; text-transform: uppercase; }}
    .screenshot-box {{ text-align: center; margin-top: 20px; border: 1px solid #e2e8f0; border-radius: 8px; padding: 15px; background: #fafafa; }}
    .screenshot-box img {{ max-width: 100%; border-radius: 6px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); }}
    .footer {{ text-align: center; margin-top: 40px; font-size: 12px; color: #94a3b8; border-top: 1px solid #f1f5f9; padding-top: 20px; }}
  </style>
</head>
<body>

<div class="report-card">
  <div class="header">
    <div>
      <h1>🕵️ Dark Pattern Compliance Audit Report</h1>
      <div class="meta">Target Domain: <strong>{url}</strong> | Generated by Multi-Modal AI Engine</div>
    </div>
    <div style="text-align:right;">
      <span class="badge" style="background:#2563eb;color:#fff;font-size:13px;padding:6px 12px;">ISO / GDPR / FTC Audit</span>
    </div>
  </div>

  <div class="risk-banner">
    <div class="risk-score">{risk_score}/100</div>
    <div class="risk-info">
      <h3>Overall Threat Classification: {risk_level}</h3>
      <p>{risk.get('summary', '')}</p>
    </div>
  </div>

  <h2>📋 Detailed Findings & Legal Regulatory Violations</h2>
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Category</th>
        <th>Conf.</th>
        <th>Modalities</th>
        <th>Evidence Collected</th>
        <th>Regulatory Citation</th>
        <th>Consumer Defense Advisory</th>
      </tr>
    </thead>
    <tbody>
      {findings_rows}
    </tbody>
  </table>

  {"<div class='screenshot-box'><h3>📸 Visual Proof Overlay</h3><img src='" + annotated_img + "' /></div>" if annotated_img else ""}

  <div class="footer">
    Multi-Modal Dark Pattern Detector v3.0 Executive Compliance Report · Generated automatically.
  </div>
</div>

</body>
</html>
"""
    return html_content
